require:
- rubocop-rake
- rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/MixinUsage:
  Exclude:
  - "bin/console"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Gemspec/RequireMFA:
  Enabled: false

Metrics/AbcSize:
  Max: 19.5

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 20

Metrics/ParameterLists:
  Max: 6

Metrics/BlockLength:
  Exclude:
  - "**/*_spec.rb"
  - "*.gemspec"
  - "lib/waylon/rspec/matchers/**/*.rb"

RSpec/MultipleExpectations:
  Max: 6

RSpec/ExampleLength:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false
