# frozen_string_literal: true

# Standard Library dependencies
require "base64"
require "benchmark"
require "digest"
require "English"
require "fileutils"
require "forwardable"
require "logger"
require "yaml"
require "singleton"
require "ostruct"
require "timeout"
require "resolv"
require "set"

# External dependencies
require "addressable/uri"
require "faraday"
require "i18n"
require "json"
require "moneta"
require "resque"
require "sinatra"

# Internal requirements
require "waylon/version"
require "waylon/config"
require "waylon/generic_exception"
require "waylon/exceptions/not_implemented_error"
require "waylon/exceptions/validation_error"
require "waylon/group"
require "waylon/logger"
require "waylon/base_component"
require "waylon/condition"
require "waylon/message"
require "waylon/route"
require "waylon/sense_registry"
require "waylon/sense"
require "waylon/skill_registry"
require "waylon/skill"
require "waylon/user"
require "waylon/conditions/black_hole"
require "waylon/conditions/default"
require "waylon/conditions/permission_denied"
require "waylon/conditions/regex"
require "waylon/routes/black_hole"
require "waylon/routes/default"
require "waylon/routes/permission_denied"
require "waylon/webhook"
